### ISSUE TITLE
How to run up the desktop program?

### ISSUE THREAD

**Issue by lnxpy** [ghost1372/CodeHubDesktop#3]
Hey Mehdi,

Hope you doing great. I have already installed VStudio 2017 on my system and want to know is there any other way to run this program up?

I meant an exe file plus it's dependencies like .NET framework and other ones.

Thanks :) :heart:

**Comment by ghost1372** [comment]
Hi @lnxpy 
make sure you installed .Net Core SDK 3.1
![op2](https://user-images.githubusercontent.com/9213496/79114645-0aa0cc80-7d99-11ea-933e-d855864816cf.gif)

![op](https://user-images.githubusercontent.com/9213496/79114765-5a7f9380-7d99-11ea-8df3-46d1997f5243.gif)

note:
self-contained mean The executable file will come with the dependencies
Framework-Dependent mean you need to install .net core 3.1 on your machine for running app.

good luck😉

**Comment by lnxpy** [comment]
You mean there is no way to create even a setup file from a project made in VStudio 2019?
Is it able to be published on VStudio 2015 or prior versions?
I'm so enthusiasm to see what my teammate just created! :smiley: :heart:

**Comment by ghost1372** [comment]
You can use any version of Visual Studio you want But on the condition that .NETCore 3.1 is installed on it, Because this project was made with .NETCore 3.1 and .NET Framework was not used.

What do you mean by setup? exe file or installer?
I created this short video to get you acquainted with how to get output
[2020-04-13_16-51-26.zip](https://github.com/CodeHub-Contributors/CodeHubDesktop/files/4469468/2020-04-13_16-51-26.zip)

**Comment by lnxpy** [comment]
Thanks man.
I have recently created the Admin API side for CodeHub core which allows admins to see snippets, suggestions, and also manage teammates.

You can also create the Log in/out part for the desktop release which leads admins.  Roots are available [here](https://github.com/CodeHub-Contributors/CodeHub#admin-api). Message [me](https://t.me/lnxpy) to give you the test admin username and assist you to create this yard.

You really deserve it. :1st_place_medal: :smiley:
Nice job. :heart:

**Comment by ghost1372** [comment]
tnx😁
